"""empty message

Revision ID: 3a97fb8c9c5d
Revises:
Create Date: 2024-09-14 13:28:43.873931

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3a97fb8c9c5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "firstname",
            existing_type=mysql.VARCHAR(length=80),
            type_=sa.String(length=120),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "lastname",
            existing_type=mysql.VARCHAR(length=80),
            type_=sa.String(length=120),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "lastname",
            existing_type=sa.String(length=120),
            type_=mysql.VARCHAR(length=80),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "firstname",
            existing_type=sa.String(length=120),
            type_=mysql.VARCHAR(length=80),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
