"""Added phone_number column to User model

Revision ID: 645875ba382c
Revises: 3a97fb8c9c5d
Create Date: 2025-02-20 23:02:03.938771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645875ba382c'
down_revision = '3a97fb8c9c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_prowler_check', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('aws_prowler_compliance_report', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('aws_prowler_compliance_report')
        batch_op.drop_column('aws_prowler_check')

    # ### end Alembic commands ###
