"""Added column to Account

Revision ID: 7f5f5ea74070
Revises: 645875ba382c
Create Date: 2025-02-20 23:45:56.939997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5f5ea74070'
down_revision = '645875ba382c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_prowler_check_date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('aws_prowler_check_date_created')

    # ### end Alembic commands ###
